/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gab_test_core_ui_sample_Core */

#ifndef _Included_com_gab_test_core_ui_sample_Core
#define _Included_com_gab_test_core_ui_sample_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gab_test_core_ui_sample_Core
 * Method:    GetNumberOfContacts
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gab_test_core_1ui_1sample_Core_GetNumberOfContacts
  (JNIEnv *, jclass);

/*
 * Class:     com_gab_test_core_ui_sample_Core
 * Method:    AddContact
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gab_test_core_1ui_1sample_Core_AddContact
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gab_test_core_ui_sample_Core
 * Method:    startWaitingContacts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gab_test_core_1ui_1sample_Core_startWaitingContacts
  (JNIEnv *, jclass);

/*
 * Class:     com_gab_test_core_ui_sample_Core
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gab_test_core_1ui_1sample_Core_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
