/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gab_test_core_ui_sample_PressMe */

#ifndef _Included_com_gab_test_core_ui_sample_PressMe
#define _Included_com_gab_test_core_ui_sample_PressMe
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gab_test_core_ui_sample_PressMe_MY_CORE_POOL_SIZE
#define com_gab_test_core_ui_sample_PressMe_MY_CORE_POOL_SIZE 10L
#undef com_gab_test_core_ui_sample_PressMe_MY_MAXIMUM_POOL_SIZE
#define com_gab_test_core_ui_sample_PressMe_MY_MAXIMUM_POOL_SIZE 21L
#undef com_gab_test_core_ui_sample_PressMe_MY_KEEP_ALIVE
#define com_gab_test_core_ui_sample_PressMe_MY_KEEP_ALIVE 1L
/*
 * Class:     com_gab_test_core_ui_sample_PressMe
 * Method:    startWaitingContacts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gab_test_core_1ui_1sample_PressMe_startWaitingContacts
  (JNIEnv *, jobject);

/*
 * Class:     com_gab_test_core_ui_sample_PressMe
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gab_test_core_1ui_1sample_PressMe_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
